driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  systems: 
    - name: local
      backend: local

platforms:
  - name: default-input-nothing-module
    driver:
      root_module_directory: test/fixtures/default_input

  - name: user-input-nothing-module
    driver:
      root_module_directory: test/fixtures/user_input
      variables:
        user_input: "test"

suites:
  - name: default-input
    includes: default-input-nothing-module
  - name: user-input
    includes: user-input-nothing-module
